### ISSUE TITLE
US 02.04.01 View recipe

### ISSUE THREAD

**Issue by CarlHat** [CMPUT301F22T16/HappyMeals#14]
As a meal planner, I want to view a recipe and its details.

**Comment by CarlHat** [comment]
### Acceptance Criteria
----

> - [ ] View recipe should be an separate activity
> - [ ] View recipe page should show a recipe picture that can be either defaulted or edited by the user.
> - [ ] View recipe page should show all the ingredients required. Click on an ingredient can view the ingredient detail.
> - [ ] View recipe page should show all the other info related to this recipe.

**Comment by shehraj123** [comment]
@JohnYu2000 @CarlHat I am extending this story to also allow Camera app pictures and a default Recipe image to be shown if the user doesnt click or select any image.

**Comment by shehraj123** [comment]
## New Acceptance Criteria

- [x] Have a camera activity to allow user to click and select new image for a recipe.
- [x] Add a default image for recipes.
