### ISSUE TITLE
US 02.05.01 Edit recipe

### ISSUE THREAD

**Issue by CarlHat** [CMPUT301F22T16/HappyMeals#16]
As a meal planner, I want to edit the details of a recipe, including the ingredients.

**Comment by CarlHat** [comment]
### Acceptance Criteria
----

> - [ ] Click edit on a recipe in the recipe list to edit the recipe.
> - [ ] Edit recipe should be a separate activity.
> - [ ] Edit recipe page should show text input fields for general info.
> - [ ] Edit recipe page should be able to select ingredients from the ingredient list.
> - [ ] Edit recipe page should have the option to add a new ingredient that is not in the ingredient list.

**Comment by MHUalberta** [comment]
Needs to be looked at again.

**Comment by shehraj123** [comment]
Completed
